# @server=http://localhost:3000/
@server=http://10.56.79.171/

GET {{server}}api/v1
Content-Type: application/json

### Signup
POST {{server}}api/v1/users/signup
Content-Type: application/json

{
	"username": "suraj2",
	"password": "suraj123"
}


### Login
POST {{server}}api/v1/users/login
Content-Type: application/json

{
	"username": "suraj2",
	"password": "suraj123"
}